name: Updater

on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:   
  update_flake:
    runs-on: native
    steps:
    - name: Set up git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global http.sslVerify "false"
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ssh-strict: false
        github-server-url: https://git.home
    - name: Update nixpkgs
      run: nix flake lock --update-input nixpkgs
    - name: Update nixos
      run: nix flake lock --update-input nixos
    - name: Update nixpkgs-wayland
      run: nix flake lock --update-input nixpkgs-wayland
    - name: Commit and push
      run: |
        if git diff --exit-code; then
          echo "Found no changes"
          exit 0
        fi
        git add .
        git commit -m "flake.lock: Update"
        git push
