name: Updater

on:
  schedule:
  - cron: '0 7 * * *'
  workflow_dispatch: {}

jobs:   
  update_flake:
    runs-on: ubuntu-20.04
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
        install_url: https://releases.nixos.org/nix/nix-2.7.0/install
    - name: Set up git
      run: |
        git config user.email bots@kidsan.dev
        git config user.name "Git Bot"
    - name: Update the flake
      run: nix flake update
    - name: Store flake.lock
      uses: actions/upload-artifact@v3
      with:
        name: flake_lock
        path: flake.lock

  push_update:
    runs-on: ubuntu-20.04
    permissions: write-all
    needs: [update_flake]
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: Restore flake.lock
      uses: actions/download-artifact@v3
      with:
        name: flake_lock
    - id: check_file_changed
      shell: pwsh
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '.lock$' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "lockfile_changed"
        Write-Host "::set-output name=lockfile_changed::$HasDiff"
    - name: Set up git
      if: steps.check_file_changed.outputs.lockfile_changed == 'True'
      run: |
        git config user.email bots@kidsan.dev
        git config user.name "Git Bot"
    - name: Create and merge PR
      if: steps.check_file_changed.outputs.lockfile_changed == 'True'
      run: |
        git switch -c updates-${{ github.run_id }}
        git commit -am "flake.lock: Update"
        git push -u origin updates-${{ github.run_id }}
        PR=$(gh pr create \
          --assignee kidsan \
          --base main \
          --body "Automatic flake update on $(date -I)" \
          --fill \
          --label bot \
          --title "Auto update $(date -I)")
        gh pr merge $PR --merge --delete-branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}